Repository CS2103JAN2018-W13-B4/main, pull requests merged in 2018-04, with the labels that each got.

#180 [#179] Fixes Calendar Tests Fails
  src/main/java/seedu/organizer/ui/calendar/MonthView.java
  src/test/java/seedu/organizer/logic/commands/PreviousMonthCommandTest.java
  src/test/java/seedu/organizer/ui/CalendarPanelTest.java
  src/test/java/seedu/organizer/ui/MonthViewTest.java
Labels: type.bug

#172 [#173] Modify DeveloperGuide - Introduction, Getting Started & Design
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/DeveloperGettingStarted1.png
  docs/images/DeveloperGettingStarted2.png
  docs/images/DeveloperGettingStarted3.png
  docs/images/DeveloperGettingStarted4.png
  docs/images/DeveloperGettingStarted5.png
  docs/images/DeveloperGettingStarted6.png
  docs/stylesheets/asciidoctor.css
  docs/stylesheets/guides-style.css
  src/test/java/seedu/organizer/ui/MonthViewTest.java
Labels: type.task

#184 [#143][#173] Developer Guide edit
  docs/DeveloperGuide.adoc
  docs/diagrams/ModelComponentClassDiagram.pptx
  docs/diagrams/UiComponentClassDiagram.pptx
  docs/images/ModelClassDiagram.png
  docs/images/UiClassDiagram.png
Labels: priority.high, type.task

#190 [#174] Rework User Guide: Layout Structure, Introduction, Quick Start & Using PrioriTask & FAQ
  docs/DeveloperGuide.adoc
  docs/DummySearchPage.html
  docs/UserGuide.adoc
  docs/images/Ui.png
  docs/images/UserGuideDifferentComponents.png
  docs/images/UserGuideQuickStart1.png
  docs/images/UserGuideQuickStart2.png
  docs/images/UserGuideQuickStart3.png
  docs/images/UserGuideQuickStart4.png
  docs/images/UserGuideQuickStart5.png
Labels: type.task

#191 [#182] Add CurrentMonthCommand
  docs/UserGuide.adoc
  src/main/java/seedu/organizer/MainApp.java
  src/main/java/seedu/organizer/commons/core/Config.java
  src/main/java/seedu/organizer/logic/commands/CurrentMonthCommand.java
  src/main/java/seedu/organizer/logic/parser/AddCommandParser.java
  src/main/java/seedu/organizer/logic/parser/OrganizerParser.java
  src/main/java/seedu/organizer/ui/StatusBarFooter.java
  src/main/java/seedu/organizer/ui/TaskCard.java
  src/main/java/seedu/organizer/ui/calendar/MonthView.java
  src/main/resources/view/CalendarPanel.fxml
  src/main/resources/view/DarkTheme.css
  src/test/java/guitests/guihandles/StatusBarFooterHandle.java
  src/test/java/guitests/guihandles/TaskCardHandle.java
  src/test/java/seedu/organizer/commons/core/ConfigTest.java
  src/test/java/seedu/organizer/logic/commands/CurrentMonthCommandTest.java
  src/test/java/seedu/organizer/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/organizer/logic/parser/OrganizerParserTest.java
  src/test/java/seedu/organizer/testutil/TypicalExecutedCommands.java
  src/test/java/seedu/organizer/ui/CalendarPanelTest.java
  src/test/java/seedu/organizer/ui/MonthViewTest.java
  src/test/java/seedu/organizer/ui/testutil/GuiTestAssert.java
Labels: type.epic, type.task

#175 Fix retrieving subtask from wrong source
  src/main/java/seedu/organizer/logic/commands/DeleteSubtaskCommand.java
  src/test/java/seedu/organizer/logic/commands/DeleteSubtaskCommandTest.java
Labels: type.bug, type.epic

#193 [#186][#187][#188] Add ForgotPasswordCommand and AnswerCommand
  docs/UserGuide.adoc
  src/main/java/seedu/organizer/logic/commands/AddQuestionAnswerCommand.java
  src/main/java/seedu/organizer/logic/commands/AnswerCommand.java
  src/main/java/seedu/organizer/logic/commands/Command.java
  src/main/java/seedu/organizer/logic/commands/FindDeadlineCommand.java
  src/main/java/seedu/organizer/logic/commands/FindDescriptionCommand.java
  src/main/java/seedu/organizer/logic/commands/FindMultipleFieldsCommand.java
  src/main/java/seedu/organizer/logic/commands/FindNameCommand.java
  src/main/java/seedu/organizer/logic/commands/ForgotPasswordCommand.java
  src/main/java/seedu/organizer/logic/commands/UndoableCommand.java
  src/main/java/seedu/organizer/logic/parser/AddQuestionAnswerCommandParser.java
  src/main/java/seedu/organizer/logic/parser/AnswerCommandParser.java
  src/main/java/seedu/organizer/logic/parser/CliSyntax.java
  src/main/java/seedu/organizer/logic/parser/ForgotPasswordCommandParser.java
  src/main/java/seedu/organizer/logic/parser/OrganizerParser.java
  src/main/java/seedu/organizer/logic/parser/ParserUtil.java
  src/main/java/seedu/organizer/model/Model.java
  src/main/java/seedu/organizer/model/ModelManager.java
  src/main/java/seedu/organizer/model/Organizer.java
  src/main/java/seedu/organizer/model/user/UniqueUserList.java
  src/main/java/seedu/organizer/model/user/User.java
  src/main/java/seedu/organizer/model/user/UserWithQuestionAnswer.java
  src/main/java/seedu/organizer/storage/XmlAdaptedUser.java
  src/main/java/seedu/organizer/storage/XmlOrganizerStorage.java
  src/main/java/seedu/organizer/storage/XmlSerializableOrganizer.java
  src/test/java/seedu/organizer/logic/commands/AddCommandTest.java
  src/test/java/seedu/organizer/logic/commands/AddQuestionAnswerCommandTest.java
  src/test/java/seedu/organizer/logic/commands/AnswerCommandTest.java
  src/test/java/seedu/organizer/logic/commands/EditCommandTest.java
  src/test/java/seedu/organizer/logic/commands/ForgotPasswordCommandTest.java
  src/test/java/seedu/organizer/logic/commands/LoginCommandTest.java
  src/test/java/seedu/organizer/logic/commands/SignUpCommandTest.java
  src/test/java/seedu/organizer/logic/parser/AddQuestionAnswerCommandParserTest.java
  src/test/java/seedu/organizer/logic/parser/AnswerCommandParserTest.java
  src/test/java/seedu/organizer/logic/parser/ForgotPasswordCommandParserTest.java
  src/test/java/seedu/organizer/model/user/UserWithQuestionAnswerTest.java
  src/test/java/seedu/organizer/storage/StorageManagerTest.java
  src/test/java/seedu/organizer/storage/XmlAdaptedUserTest.java
  src/test/java/systemtests/AddCommandSystemTest.java
  src/test/java/systemtests/ClearCommandSystemTest.java
  src/test/java/systemtests/DeleteCommandSystemTest.java
  src/test/java/systemtests/EditCommandSystemTest.java
  src/test/java/systemtests/ErrorDialogGuiTest.java
  src/test/java/systemtests/FindNameCommandSystemTest.java
  src/test/java/systemtests/SelectCommandSystemTest.java
Labels: type.task

#196 [#195] Collate Annotated Code
  collated/functional/dominickenn.md
  collated/functional/guekling.md
  collated/functional/natania.md
  collated/test/dominickenn.md
  collated/test/guekling.md
  collated/test/natania-reused.md
  src/main/java/seedu/organizer/model/task/DateAdded.java
Labels: type.task

#198 [#173] Rework Developer Guide: Undo/Redo Implementation
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
Labels: type.task

#200 [#174] Update TODO and language check.
  docs/UserGuide.adoc
Labels: priority.high, type.task

#202 [#174] User Guide: Update Calendar Features
  README.adoc
  docs/UserGuide.adoc
  docs/images/UserGuideCalendarFeature1.png
Labels: type.task

#201 [#132] DeveloperGuide: Add Calendar Implementation
  docs/DeveloperGuide.adoc
  docs/diagrams/CalendarCommandExecutionSequenceDiagram.pptx
  docs/diagrams/CalendarComponentClassDiagram.pptx
  docs/diagrams/CalendarSequenceDiagram.pptx
  docs/images/CalendarCommandExecutionSequenceDiagram.png
  docs/images/CalendarComponentClassDiagram.png
  docs/images/CalendarSequenceDiagram.png
  src/main/java/seedu/organizer/logic/Logic.java
  src/main/java/seedu/organizer/ui/calendar/EntryCard.java
Labels: type.task

#204 [#203] Fix logout bug
  src/main/java/seedu/organizer/logic/UndoRedoStack.java
  src/main/java/seedu/organizer/logic/commands/LogoutCommand.java
  src/main/java/seedu/organizer/model/ModelManager.java
  src/test/java/seedu/organizer/logic/UndoRedoStackTest.java
Labels: type.bug

#211 [#210] Fix App does not appear bug
  src/main/java/seedu/organizer/MainApp.java
  src/main/java/seedu/organizer/commons/core/GuiSettings.java
  src/main/java/seedu/organizer/logic/commands/ExitCommand.java
  src/main/java/seedu/organizer/storage/Storage.java
  src/main/java/seedu/organizer/ui/MainWindow.java
  src/main/java/seedu/organizer/ui/UiManager.java
Labels: type.bug

#215 [#213] Fix login bug
  src/main/java/seedu/organizer/logic/commands/LoginCommand.java
  src/main/java/seedu/organizer/model/Model.java
  src/main/java/seedu/organizer/model/ModelManager.java
  src/main/java/seedu/organizer/model/Organizer.java
  src/main/java/seedu/organizer/model/user/UniqueUserList.java
  src/main/java/seedu/organizer/model/user/User.java
  src/main/java/seedu/organizer/model/user/exceptions/UserPasswordWrongException.java
  src/test/java/seedu/organizer/TestApp.java
  src/test/java/seedu/organizer/logic/LogicManagerTest.java
  src/test/java/seedu/organizer/logic/commands/AddQuestionAnswerCommandTest.java
  src/test/java/seedu/organizer/logic/commands/AddSubtaskCommandTest.java
  src/test/java/seedu/organizer/logic/commands/ClearCommandTest.java
  src/test/java/seedu/organizer/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/organizer/logic/commands/DeleteSubtaskCommandTest.java
  src/test/java/seedu/organizer/logic/commands/EditCommandTest.java
  src/test/java/seedu/organizer/logic/commands/FindDeadlineCommandTest.java
  src/test/java/seedu/organizer/logic/commands/FindDescriptionCommandTest.java
  src/test/java/seedu/organizer/logic/commands/FindMultipleFieldsCommandTest.java
  src/test/java/seedu/organizer/logic/commands/FindNameCommandTest.java
  src/test/java/seedu/organizer/logic/commands/ListCommandTest.java
  src/test/java/seedu/organizer/logic/commands/ListCompletedTasksCommandTest.java
  src/test/java/seedu/organizer/logic/commands/ListUncompletedTasksCommandTest.java
  src/test/java/seedu/organizer/logic/commands/LoginCommandTest.java
  src/test/java/seedu/organizer/logic/commands/RedoCommandTest.java
  src/test/java/seedu/organizer/logic/commands/SelectCommandTest.java
  src/test/java/seedu/organizer/logic/commands/ToggleCommandTest.java
  src/test/java/seedu/organizer/logic/commands/ToggleSubtaskCommandTest.java
  src/test/java/seedu/organizer/logic/commands/UndoCommandTest.java
  src/test/java/seedu/organizer/logic/commands/UndoableCommandTest.java
  src/test/java/seedu/organizer/logic/parser/AddQuestionAnswerCommandParserTest.java
  src/test/java/seedu/organizer/logic/parser/OrganizerParserLoggedInTest.java
  src/test/java/seedu/organizer/model/ModelManagerTest.java
  src/test/java/seedu/organizer/model/user/UserTest.java
  src/test/java/seedu/organizer/ui/CommandBoxTest.java
  src/test/java/systemtests/AddCommandSystemTest.java
  src/test/java/systemtests/ClearCommandSystemTest.java
  src/test/java/systemtests/DeleteCommandSystemTest.java
  src/test/java/systemtests/EditCommandSystemTest.java
  src/test/java/systemtests/ErrorDialogGuiTest.java
  src/test/java/systemtests/FindNameCommandSystemTest.java
  src/test/java/systemtests/SelectCommandSystemTest.java
Labels: type.bug

#235 [#233][#216] Delete select command
  docs/UserGuide.adoc
  src/main/java/seedu/organizer/MainApp.java
  src/main/java/seedu/organizer/commons/events/ui/TaskPanelSelectionChangedEvent.java
  src/main/java/seedu/organizer/logic/commands/AddCommand.java
  src/main/java/seedu/organizer/logic/commands/AddQuestionAnswerCommand.java
  src/main/java/seedu/organizer/logic/commands/ClearCommand.java
  src/main/java/seedu/organizer/logic/commands/DeleteCommand.java
  src/main/java/seedu/organizer/logic/commands/EditCommand.java
  src/main/java/seedu/organizer/logic/commands/FindDescriptionCommand.java
  src/main/java/seedu/organizer/logic/commands/FindMultipleFieldsCommand.java
  src/main/java/seedu/organizer/logic/commands/FindNameCommand.java
  src/main/java/seedu/organizer/logic/commands/SelectCommand.java
  src/main/java/seedu/organizer/logic/parser/OrganizerParser.java
  src/main/java/seedu/organizer/logic/parser/SelectCommandParser.java
  src/main/java/seedu/organizer/model/ModelManager.java
  src/main/java/seedu/organizer/model/Organizer.java
  src/main/java/seedu/organizer/model/ReadOnlyOrganizer.java
  src/main/java/seedu/organizer/model/tag/Tag.java
  src/main/java/seedu/organizer/model/task/DateAdded.java
  src/main/java/seedu/organizer/model/task/DateCompleted.java
  src/main/java/seedu/organizer/model/task/Deadline.java
  src/main/java/seedu/organizer/model/task/Description.java
  src/main/java/seedu/organizer/model/task/Name.java
  src/main/java/seedu/organizer/model/task/Status.java
  src/main/java/seedu/organizer/model/task/Task.java
  src/main/java/seedu/organizer/storage/XmlFileStorage.java
  src/main/java/seedu/organizer/ui/TaskListPanel.java
  src/test/java/guitests/guihandles/TaskListPanelHandle.java
  src/test/java/seedu/organizer/logic/LogicManagerTest.java
  src/test/java/seedu/organizer/logic/commands/AnswerCommandTest.java
  src/test/java/seedu/organizer/logic/commands/CommandTestUtil.java
  src/test/java/seedu/organizer/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/organizer/logic/commands/EditCommandTest.java
  src/test/java/seedu/organizer/logic/commands/SelectCommandTest.java
  src/test/java/seedu/organizer/logic/parser/OrganizerParserLoggedInTest.java
  src/test/java/seedu/organizer/logic/parser/SelectCommandParserTest.java
  src/test/java/seedu/organizer/ui/StatusBarFooterTest.java
  src/test/java/systemtests/AddCommandSystemTest.java
  src/test/java/systemtests/ClearCommandSystemTest.java
  src/test/java/systemtests/DeleteCommandSystemTest.java
  src/test/java/systemtests/EditCommandSystemTest.java
  src/test/java/systemtests/ErrorDialogGuiTest.java
  src/test/java/systemtests/FindNameCommandSystemTest.java
  src/test/java/systemtests/HelpCommandSystemTest.java
  src/test/java/systemtests/OrganizerSystemTest.java
  src/test/java/systemtests/SelectCommandSystemTest.java
  src/uncommentedsystemtests/AddCommandSystemTest.java
  src/uncommentedsystemtests/ClearCommandSystemTest.java
  src/uncommentedsystemtests/DeleteCommandSystemTest.java
  src/uncommentedsystemtests/EditCommandSystemTest.java
  src/uncommentedsystemtests/FindNameCommandSystemTest.java
  src/uncommentedsystemtests/HelpCommandSystemTest.java
  src/uncommentedsystemtests/OrganizerSystemTest.java
  src/uncommentedsystemtests/SelectCommandSystemTest.java
Labels: type.task

#237 [#220] Fix bug in Calendar commands
  src/main/java/seedu/organizer/logic/LogicManager.java
Labels: type.bug

#239 [#217][#219][#221][#222][#231][#236] Fix login feature related bugs.
  docs/UserGuide.adoc
  src/main/java/seedu/organizer/logic/CommandHistory.java
  src/main/java/seedu/organizer/logic/commands/AddQuestionAnswerCommand.java
  src/main/java/seedu/organizer/logic/commands/AnswerCommand.java
  src/main/java/seedu/organizer/logic/commands/Command.java
  src/main/java/seedu/organizer/logic/commands/LoginCommand.java
  src/main/java/seedu/organizer/logic/commands/LogoutCommand.java
  src/main/java/seedu/organizer/logic/commands/SignUpCommand.java
  src/main/java/seedu/organizer/logic/parser/ParserUtil.java
  src/main/java/seedu/organizer/model/user/User.java
  src/main/java/seedu/organizer/model/user/UserWithQuestionAnswer.java
  src/main/java/seedu/organizer/storage/XmlAdaptedTask.java
  src/main/java/seedu/organizer/storage/XmlAdaptedUser.java
  src/test/java/seedu/organizer/logic/commands/AnswerCommandTest.java
  src/test/java/seedu/organizer/logic/commands/LoginCommandTest.java
  src/test/java/seedu/organizer/logic/commands/SignUpCommandTest.java
  src/test/java/seedu/organizer/logic/parser/AddQuestionAnswerCommandParserTest.java
  src/test/java/seedu/organizer/logic/parser/LoginCommandParserTest.java
  src/test/java/seedu/organizer/logic/parser/ParserUtilTest.java
  src/test/java/seedu/organizer/logic/parser/SignUpCommandParserTest.java
  src/test/java/seedu/organizer/model/task/predicates/TaskByUserPredicateTest.java
  src/test/java/seedu/organizer/model/user/UserWithQuestionAnswerTest.java
Labels: type.bug

#240 [#234] Add isValidDate to fix deadline bugs
  docs/UserGuide.adoc
  src/main/java/seedu/organizer/model/task/DateAdded.java
  src/main/java/seedu/organizer/model/task/DateCompleted.java
  src/main/java/seedu/organizer/model/task/Deadline.java
  src/test/java/seedu/organizer/model/task/DateAddedTest.java
  src/test/java/seedu/organizer/model/task/DeadlineTest.java
Labels: type.bug

#244 [#232][#218] Update UserGuide to Reflect Deadline Parameter Constraints
  docs/UserGuide.adoc
  src/main/resources/view/MonthView.fxml
Labels: type.bug

#243 [#242] Rework priority autoupdating formula.
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  src/main/java/seedu/organizer/model/task/UniqueTaskList.java
Labels: type.bug

#247 [#226][#246] Add UI to replace total tasks with currently logged in user.
  src/main/java/seedu/organizer/model/Organizer.java
  src/main/java/seedu/organizer/model/ReadOnlyOrganizer.java
  src/main/java/seedu/organizer/ui/MainWindow.java
  src/main/java/seedu/organizer/ui/StatusBarFooter.java
  src/main/resources/view/StatusBarFooter.fxml
  src/test/java/guitests/guihandles/StatusBarFooterHandle.java
  src/test/java/seedu/organizer/model/OrganizerTest.java
  src/test/java/seedu/organizer/ui/StatusBarFooterTest.java
  src/test/java/systemtests/OrganizerSystemTest.java
  src/uncommentedsystemtests/OrganizerSystemTest.java
Labels: type.task

#252 [#250][#251] Fix typo in XmlAdaptedTask and DateCompleted
  src/main/java/seedu/organizer/model/task/DateAdded.java
  src/main/java/seedu/organizer/model/task/DateCompleted.java
  src/main/java/seedu/organizer/storage/XmlAdaptedTask.java
Labels: type.bug

#253 [#224][#228] Edit MESSAGE_USAGE
  docs/UserGuide.adoc
  src/main/java/seedu/organizer/logic/commands/ToggleCommand.java
  src/main/java/seedu/organizer/logic/commands/ToggleSubtaskCommand.java
  src/main/java/seedu/organizer/model/task/Status.java
Labels: type.bug

#256 Code style check and Project Portfolio for Dominic (V1.0)
  collated/functional/dominickenn.md
  collated/test/dominickenn.md
  docs/team/dominic.adoc
  src/main/java/seedu/organizer/logic/CommandHistory.java
  src/main/java/seedu/organizer/logic/commands/AddQuestionAnswerCommand.java
  src/main/java/seedu/organizer/logic/commands/AnswerCommand.java
  src/main/java/seedu/organizer/logic/commands/ForgotPasswordCommand.java
  src/main/java/seedu/organizer/logic/commands/ListCompletedTasksCommand.java
  src/main/java/seedu/organizer/logic/commands/ListUncompletedTasksCommand.java
  src/main/java/seedu/organizer/logic/commands/LoginCommand.java
  src/main/java/seedu/organizer/logic/commands/LogoutCommand.java
  src/main/java/seedu/organizer/logic/commands/SignUpCommand.java
  src/main/java/seedu/organizer/logic/parser/AddCommandParser.java
  src/main/java/seedu/organizer/logic/parser/AddQuestionAnswerCommandParser.java
  src/main/java/seedu/organizer/logic/parser/AnswerCommandParser.java
  src/main/java/seedu/organizer/logic/parser/ForgotPasswordCommandParser.java
  src/main/java/seedu/organizer/logic/parser/LoginCommandParser.java
  src/main/java/seedu/organizer/logic/parser/ParserUtil.java
  src/main/java/seedu/organizer/logic/parser/SignUpCommandParser.java
  src/main/java/seedu/organizer/model/Model.java
  src/main/java/seedu/organizer/model/ModelManager.java
  src/main/java/seedu/organizer/model/Organizer.java
  src/main/java/seedu/organizer/model/task/DateAdded.java
  src/main/java/seedu/organizer/model/task/DateCompleted.java
  src/main/java/seedu/organizer/model/task/Priority.java
  src/main/java/seedu/organizer/model/task/Task.java
  src/main/java/seedu/organizer/model/task/UniqueTaskList.java
  src/main/java/seedu/organizer/model/task/predicates/TaskByStatusPredicate.java
  src/main/java/seedu/organizer/model/user/UniqueUserList.java
  src/main/java/seedu/organizer/model/user/User.java
  src/main/java/seedu/organizer/model/user/UserWithQuestionAnswer.java
  src/main/java/seedu/organizer/model/user/exceptions/DuplicateUserException.java
  src/main/java/seedu/organizer/model/user/exceptions/UserNotFoundException.java
  src/main/java/seedu/organizer/storage/XmlAdaptedUser.java
  src/main/java/seedu/organizer/ui/MainWindow.java
  src/main/java/seedu/organizer/ui/TaskListPanel.java
  src/test/java/seedu/organizer/TestApp.java
  src/test/java/seedu/organizer/logic/commands/AddQuestionAnswerCommandTest.java
  src/test/java/seedu/organizer/logic/commands/AnswerCommandTest.java
  src/test/java/seedu/organizer/logic/commands/ForgotPasswordCommandTest.java
  src/test/java/seedu/organizer/logic/commands/ListCompletedTasksCommandTest.java
  src/test/java/seedu/organizer/logic/commands/ListUncompletedTasksCommandTest.java
  src/test/java/seedu/organizer/logic/commands/LoginCommandTest.java
  src/test/java/seedu/organizer/logic/commands/SignUpCommandTest.java
  src/test/java/seedu/organizer/logic/parser/AnswerCommandParserTest.java
  src/test/java/seedu/organizer/logic/parser/ForgotPasswordCommandParserTest.java
  src/test/java/seedu/organizer/logic/parser/LoginCommandParserTest.java
  src/test/java/seedu/organizer/logic/parser/OrganizerParserLoggedInTest.java
  src/test/java/seedu/organizer/logic/parser/OrganizerParserNotLoggedInTest.java
  src/test/java/seedu/organizer/logic/parser/SignUpCommandParserTest.java
  src/test/java/seedu/organizer/model/UniqueTaskListTest.java
  src/test/java/seedu/organizer/model/task/TaskCreatedContainsDateAddedTest.java
  src/test/java/seedu/organizer/model/user/UserTest.java
  src/test/java/systemtests/ErrorDialogGuiTest.java
  src/uncommentedsystemtests/OrganizerSystemTest.java
Labels: type.task

#258 Update Project Portfolio Page
  docs/UserGuide.adoc
  docs/team/guekling.adoc
  docs/team/johndoe.adoc
Labels: type.task

#192 Create RecurWeeklyCommand without logic yet
  docs/UserGuide.adoc
  src/main/java/seedu/organizer/logic/commands/AddCommand.java
  src/main/java/seedu/organizer/logic/commands/AddSubtaskCommand.java
  src/main/java/seedu/organizer/logic/commands/DeleteSubtaskCommand.java
  src/main/java/seedu/organizer/logic/commands/EditCommand.java
  src/main/java/seedu/organizer/logic/commands/RecurWeeklyCommand.java
  src/main/java/seedu/organizer/logic/commands/ToggleCommand.java
  src/main/java/seedu/organizer/logic/commands/ToggleSubtaskCommand.java
  src/main/java/seedu/organizer/logic/parser/CliSyntax.java
  src/main/java/seedu/organizer/logic/parser/OrganizerParser.java
  src/main/java/seedu/organizer/logic/parser/ParserUtil.java
  src/main/java/seedu/organizer/logic/parser/RecurWeeklyCommandParser.java
  src/main/java/seedu/organizer/model/Model.java
  src/main/java/seedu/organizer/model/ModelManager.java
  src/main/java/seedu/organizer/model/Organizer.java
  src/main/java/seedu/organizer/model/recurrence/Recurrence.java
  src/main/java/seedu/organizer/model/recurrence/exceptions/TaskAlreadyRecurredException.java
  src/main/java/seedu/organizer/model/subtask/UniqueSubtaskList.java
  src/main/java/seedu/organizer/model/task/Task.java
  src/main/java/seedu/organizer/model/task/UniqueTaskList.java
  src/main/java/seedu/organizer/storage/XmlAdaptedRecurrence.java
  src/main/java/seedu/organizer/storage/XmlAdaptedTask.java
  src/main/java/seedu/organizer/ui/TaskCard.java
  src/test/data/XmlSerializableOrganizerTest/typicalTasksOrganizer.xml
  src/test/data/XmlUtilTest/invalidTaskField.xml
  src/test/data/XmlUtilTest/missingTaskField.xml
  src/test/data/XmlUtilTest/validOrganizer.xml
  src/test/data/XmlUtilTest/validTask.xml
  src/test/java/seedu/organizer/commons/util/XmlUtilTest.java
  src/test/java/seedu/organizer/logic/commands/AddCommandTest.java
  src/test/java/seedu/organizer/logic/commands/AddSubtaskCommandTest.java
  src/test/java/seedu/organizer/logic/commands/DeleteSubtaskCommandTest.java
  src/test/java/seedu/organizer/logic/commands/LoginCommandTest.java
  src/test/java/seedu/organizer/logic/commands/SignUpCommandTest.java
  src/test/java/seedu/organizer/logic/commands/ToggleCommandTest.java
  src/test/java/seedu/organizer/logic/commands/ToggleSubtaskCommandTest.java
  src/test/java/seedu/organizer/storage/XmlAdaptedTaskTest.java
  src/test/java/seedu/organizer/testutil/EditTaskDescriptorBuilder.java
  src/test/java/seedu/organizer/testutil/TaskBuilder.java
  src/test/java/seedu/organizer/testutil/TaskUtil.java
  src/test/java/seedu/organizer/ui/EntryCardTest.java
  src/test/java/seedu/organizer/ui/testutil/GuiTestAssert.java
  src/test/java/systemtests/FindNameCommandSystemTest.java
Labels: priority.high, type.story

#257 Add portfolio
  docs/UserGuide.adoc
  docs/team/agus.adoc
Labels: type.task

#260 [#241] Fix Calendar Display Issue
  src/main/resources/view/MonthView.fxml
Labels: type.bug

#261 Add command parser test bug fix
  src/test/java/seedu/organizer/logic/parser/AddCommandParserTest.java
Labels: type.bug

#249 [#223] Fix Multiple Prefixes for Task Commands
  docs/UserGuide.adoc
  src/main/java/seedu/organizer/commons/core/Messages.java
  src/main/java/seedu/organizer/logic/parser/AddCommandParser.java
  src/main/java/seedu/organizer/logic/parser/AddQuestionAnswerCommandParser.java
  src/main/java/seedu/organizer/logic/parser/AnswerCommandParser.java
  src/main/java/seedu/organizer/logic/parser/ArgumentMultimap.java
  src/main/java/seedu/organizer/logic/parser/EditCommandParser.java
  src/main/java/seedu/organizer/logic/parser/LoginCommandParser.java
  src/main/java/seedu/organizer/logic/parser/SignUpCommandParser.java
  src/main/resources/view/CalendarPanel.fxml
  src/main/resources/view/MonthView.fxml
  src/test/java/seedu/organizer/logic/commands/CommandTestUtil.java
  src/test/java/seedu/organizer/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/organizer/logic/parser/AddQuestionAnswerCommandParserTest.java
  src/test/java/seedu/organizer/logic/parser/AnswerCommandParserTest.java
  src/test/java/seedu/organizer/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/organizer/logic/parser/LoginCommandParserTest.java
  src/test/java/seedu/organizer/logic/parser/SignUpCommandParserTest.java
Labels: type.bug

#262 Update Dominic's Project Portfolio
  docs/UserGuide.adoc
  docs/team/dominic.adoc
Labels: type.task

#265 [#248] Add to Appendix F of DG
  collated/functional/dominickenn.md
  collated/test/dominickenn.md
  docs/DeveloperGuide.adoc
  src/main/java/seedu/organizer/logic/commands/ForgotPasswordCommand.java
  src/test/java/seedu/organizer/logic/commands/ForgotPasswordCommandTest.java
Labels: type.task

#267 Fix UGDG Issues
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/UserGuideCalendarFeature1.png
  docs/images/UserGuideCalendarFeature2.png
  docs/images/UserGuideDifferentComponents.png
  docs/images/UserGuideQuickStart2.png
  docs/images/UserGuideQuickStart3.png
  docs/images/UserGuideQuickStart4.png
  docs/images/UserGuideQuickStart5.png
Labels: type.task

#271 Remove Unnecessary Code, Update Docs
  docs/DeveloperGuide.adoc
  docs/team/guekling.adoc
  src/main/java/seedu/organizer/model/task/Deadline.java
Labels: type.task

#273 Collate Code, Update Docs
  collated/functional/agus.md
  collated/functional/dominickenn.md
  collated/functional/guekling.md
  collated/functional/natania-reused.md
  collated/functional/natania.md
  collated/test/agus.md
  collated/test/dominickenn.md
  collated/test/guekling.md
  collated/test/natania-reused.md
  collated/test/natania.md
  docs/UserGuide.adoc
  docs/team/guekling.adoc
Labels: type.task

#275 Update Dominic's PPP
  docs/team/dominic.adoc
Labels: type.task

#276 Update version number to v1.5
  src/main/java/seedu/organizer/MainApp.java
Labels: type.task

#278 Update Dominic's PPP.
  docs/team/dominic.adoc
Labels: type.task
