Repository CS2103JAN2018-W13-B4/main, pull requests merged in 2018-03, with the labels that each got.

#18 DeveloperGuide v1.0: Edit Target User Profile, Value Proposition & NFR
  docs/DeveloperGuide.adoc
Labels: priority.high, type.task

#16 [#3, #8] UserGuide v1.0: Rework Introduction, Quick Start & Command Summary sections
  docs/UserGuide.adoc
Labels: priority.high, type.task

#86 [#83][#84][#85][#60] Add automatic priority level setting to addCommand
  docs/UserGuide.adoc
  src/main/java/seedu/organizer/logic/parser/AddCommandParser.java
  src/test/java/seedu/organizer/logic/parser/AddCommandParserTest.java
  src/test/java/systemtests/AddCommandSystemTest.java
Labels: priority.medium, type.task

#93 [#91][#92][#90] Add automatic task sorting according to priority level
  docs/DeveloperGuide.adoc
  src/main/java/seedu/organizer/model/task/Task.java
  src/main/java/seedu/organizer/model/task/UniqueTaskList.java
  src/main/java/seedu/organizer/model/util/SampleDataUtil.java
  src/test/java/seedu/organizer/logic/commands/CommandTestUtil.java
  src/test/java/seedu/organizer/model/OrganizerTest.java
  src/test/java/systemtests/EditCommandSystemTest.java
Labels: priority.high, type.story, type.task

#165 [#158] Add PreviousMonthCommand
  docs/UserGuide.adoc
  src/main/java/seedu/organizer/logic/Logic.java
  src/main/java/seedu/organizer/logic/LogicManager.java
  src/main/java/seedu/organizer/logic/commands/ListCommand.java
  src/main/java/seedu/organizer/logic/commands/PreviousMonthCommand.java
  src/main/java/seedu/organizer/logic/parser/OrganizerParser.java
  src/main/java/seedu/organizer/ui/CalendarPanel.java
  src/main/java/seedu/organizer/ui/MainWindow.java
  src/main/java/seedu/organizer/ui/calendar/Calendar.java
  src/main/java/seedu/organizer/ui/calendar/MonthView.java
  src/main/resources/view/Calendar.fxml
  src/test/java/seedu/organizer/logic/parser/OrganizerParserTest.java
  src/test/java/systemtests/AddCommandSystemTest.java
  src/test/java/systemtests/EditCommandSystemTest.java
  src/test/java/systemtests/FindNameCommandSystemTest.java
Labels: type.task

#167 [#147] Calendar Tests
  src/main/java/seedu/organizer/ui/CalendarPanel.java
  src/main/java/seedu/organizer/ui/calendar/EntryCard.java
  src/main/java/seedu/organizer/ui/calendar/MonthView.java
  src/test/java/guitests/GuiRobot.java
  src/test/java/guitests/guihandles/CalendarPanelHandle.java
  src/test/java/guitests/guihandles/EntryCardHandle.java
  src/test/java/guitests/guihandles/MonthViewHandle.java
  src/test/java/guitests/guihandles/WebViewUtil.java
  src/test/java/seedu/organizer/logic/commands/CommandTestUtil.java
  src/test/java/seedu/organizer/logic/commands/PreviousMonthCommandTest.java
  src/test/java/seedu/organizer/testutil/TypicalExecutedCommands.java
  src/test/java/seedu/organizer/ui/CalendarPanelTest.java
  src/test/java/seedu/organizer/ui/EntryCardTest.java
  src/test/java/seedu/organizer/ui/MonthViewTest.java
  src/test/java/seedu/organizer/ui/testutil/GuiTestAssert.java
  src/test/java/systemtests/HelpCommandSystemTest.java
  src/test/java/systemtests/OrganizerSystemTest.java
Labels: type.task
